<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ReceiptTap.App</RootNamespace>
    <AssemblyName>ReceiptTap</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReceiptTap.Core\ReceiptTap.Core.csproj" />
  </ItemGroup>

</Project>
